#!/bin/bash
PROJ_NAME=pydatomic
PROJ_DIR=$HOME/repo/pydatomic

VENV_ROOT=$HOME/.venv
VENV_HOME=$VENV_ROOT/$PROJ_NAME
SITE_PACKAGES=$VENV_HOME/lib/python3.3/site-packages/
ACTIVATE_FILE=$VENV_HOME/bin/activate

pushd $PROJ_DIR > /dev/null
if [ ! -e $VENV_ROOT ]
then
	mkdir -p VENV_ROOT
fi


if [ -e $ACTIVATE_FILE ]
then
	pyvenv-3.3 --upgrade $VENV_HOME
else
	python3.3 -m venv $VENV_HOME
fi
source $ACTIVATE_FILE;
if [ ! -e $SITE_PACKAGES/distribute*.egg ]
then
	curl http://python-distribute.org/distribute_setup.py -o "/tmp/distribute_setup.py"
	python /tmp/distribute_setup.py
fi
if [ ! -e $SITE_PACKAGES/pip ]
then
	curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py -o "/tmp/get-pip.py"
	python /tmp/get-pip.py
fi

pushd $PROJ_DIR
NEW_HASH=$(openssl md5 requirements.txt | sed "s/^.*= *//" )
OLD_HASH=$(openssl md5 $VENV_HOME/requirements.txt | sed "s/^.*= *//" ) || ""
if [ "$OLD_HASH" != "$NEW_HASH" ]
then
	pip-3.3 install -r requirements.txt
	cp requirements.txt $VENV_HOME/.
	pushd $PROJ_DIR
		python setup.py install
	popd
fi
popd > /dev/null
